logging.level.root=DEBUG

spring.application.name=rate-provider
server.port=8085

spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500

spring.cloud.consul.discovery.prefer-ip-address=true
spring.cloud.consul.discovery.health-check-path=/actuator/health
spring.cloud.consul.discovery.instance-id=${spring.application.name}:${server.port}

management.endpoints.web.exposure.include=health,info
