logging.level.root=INFO

spring.application.name=rate-provider
server.port=8085

spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500

spring.cloud.consul.discovery.prefer-ip-address=true
spring.cloud.consul.discovery.health-check-path=/actuator/health
spring.cloud.consul.discovery.instance-id=${spring.application.name}:${spring.application.instance_id:${random.uuid}}

management.endpoints.web.exposure.include=health,info,prometheus
management.info.build.enabled=true
management.metrics.tags.application=${spring.application.name}
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.percentiles.http.server.requests=0.5,0.90
